### ISSUE TITLE
OverFlow Problem

### ISSUE THREAD

**Issue by sulaemansantoso** [Bernardi23/search_map_place#8] opened 2019-12-17 09:39 UTC
The widget overflows on initial launch by several pixel

**Comment by TheScottishFly** [comment] 2019-12-25 15:21
I solved the problem : https://github.com/Bernardi23/search_map_place/pull/9

**Comment by luckyhandler** [comment] 2020-01-02 20:39
is this going to be merged?

**Comment by Bernardi23** [comment] 2020-01-03 21:59
I'm currently traveling. I'll take a look as soon as I get back home and, if everything is working fine, I'll be merging. This is weird though, because I tested it on multiple device sizes and everything looked fine. Maybe the new updates broke it.

**Comment by peterWilson34** [comment] 2020-01-13 17:20
> I solved the problem : #9

Thanks @TheScottishFly  I've downloaded your fork and it works fine.

**Comment by cfregin** [comment] 2020-01-23 14:46
Not for me. I am on Flutter beta channel.

**Comment by JsanchezPilo** [comment] 2020-02-07 17:19
it helped me thank you, you should merge it.

**Comment by Yunus0or1** [comment] 2020-03-08 09:32
I am facing same overflow problem. Although I copy pasted whole code.

**Comment by clerdson** [comment] 2020-03-24 21:00
problem overflow Expanded(child:child)

**Comment by Bernardi23** [comment] 2020-03-26 23:02
Hey guys. I’m sorry for taking so long to update this. All of you who are still having the issue, what device are you using (and what are its dimensions)?

**Comment by luckyhandler** [comment] 2020-03-27 07:19
I think this is reproducible on nearly all Android devices.

**Comment by lorenzorheinicke** [comment] 2020-03-27 12:10
> Hey guys. I’m sorry for taking so long to update this. All of you who are still having the issue, what device are you using (and what are its dimensions)?

I'm getting this issue in the iOS Simulator  (iPhone 11 Pro Max)

**Comment by Bernardi23** [comment] 2020-03-27 18:25
Like Ive said before, this is weird because I tested it on multiple device sizes, but I’ll test it again since this might be happening due to updates.

Also I don’t have a Mac to test it on IOS.

**Comment by luckyhandler** [comment] 2020-03-27 18:50
> Like Ive said before, this is weird because I tested it on multiple device sizes, but I’ll test it again since this might be happening due to updates.
> 
> Also I don’t have a Mac to test it on IOS.

So to give you two devices: I could reproduce this issue on a Sony Xperia Xz3 and on a Oneplus 5

**Comment by fettespferd** [comment] 2020-04-04 17:38
I have the same problem on huawei p30 pro. Thanks for fixing soon ;)

**Closed as completed** 2020-04-12 15:25 UTC

**Comment by Bernardi23** [comment] 2020-04-12 15:26
Version 0.3.0 should now be available, where there were not only bug fixes (like this one), but also a few other changes.
